language: node_js

node_js:
  - "8"

services:
  - docker

env:
  global:
    - BRANCH=${TRAVIS_BRANCH}
    - TAG=${TRAVIS_TAG}
    - SHA=${TRAVIS_COMMIT}
    - DO_RELEASE=if ([ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]) || [ ! -z "$TRAVIS_TAG" ];  then echo "true"; else echo "false"; fi

script:
  # build, create docker image and upload to dockerhub
  - if [["$DO_RELEASE" == true]];  then make release; else make all; fi
